<a href="https://colab.research.google.com/github/jaimetrdev/anon-ecommerce-website/blob/master/Copia_de_C2_Machine_Learning_Example.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## DATA INGESTION

---


<font color='red'> Google Drive Set-Up </font>


---

In [ ]:
# from google.colab import drive
# drive.mount('/content/drive')

---


<font color='red'> Kaggle Set-Up </font>


---

In [ ]:
# Install Kaggle in Colab:

!pip install -U -q kaggle

In [ ]:
# Create a folder named 'kaggle' in root folder:

!mkdir -p ~/.kaggle

In [ ]:
# Upload kaggle.json to Colab:

from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json

{'kaggle.json': b'{"username":"thevictor23","key":"c8968e0d3f1fb2d658fbf2fe8e3e7b1f"}'}

In [ ]:
# Copy kaggle.json into kaggle folder created above:

!cp kaggle.json ~/.kaggle/

In [ ]:
# API COMMAND

!kaggle datasets download -d uciml/pima-indians-diabetes-database

Warning: Your Kaggle API key is readable by other users on this system! To fix this, you can run 'chmod 600 /root/.kaggle/kaggle.json'
Downloading pima-indians-diabetes-database.zip to /content
  0% 0.00/8.91k [00:00<?, ?B/s]
100% 8.91k/8.91k [00:00<00:00, 7.37MB/s]

In [ ]:
!apt install pv

Reading package lists... Done
Building dependency tree
Reading state information... Done
The following package was automatically installed and is no longer required:
  libnvidia-common-460
Use 'apt autoremove' to remove it.
Suggested packages:
  doc-base
The following NEW packages will be installed:
  pv
0 upgraded, 1 newly installed, 0 to remove and 32 not upgraded.
Need to get 48.3 kB of archives.
After this operation, 123 kB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu bionic/main amd64 pv amd64 1.6.6-1 [48.3 kB]
Fetched 48.3 kB in 1s (50.6 kB/s)
Selecting previously unselected package pv.
(Reading database ... 155685 files and directories currently installed.)
Preparing to unpack .../archives/pv_1.6.6-1_amd64.deb ...
Unpacking pv (1.6.6-1) ...
Setting up pv (1.6.6-1) ...
Processing triggers for man-db (2.8.3-2ubuntu0.1) ...

In [ ]:
#**************************************************
# UNZIPPING DATASET

#  kaggle datasets download -d uciml/pima-indians-diabetes-database

# !unzip /content/zddtpgzv63-4.zip

!unzip -o /content/pima-indians-diabetes-database.zip -d /content/data | pv -l >/dev/nul

2.00  0:00:00 [ 279 /s] [ <=>                                                  ]

## EDA - EXPLORATORY DATA ANALYSIS

In [ ]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

In [ ]:
diabetes_data = pd.read_csv("diabetes.csv")

In [ ]:
diabetes_data

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
0,6,148,72,35,0,33.6,0.627,50,1
1,1,85,66,29,0,26.6,0.351,31,0
2,8,183,64,0,0,23.3,0.672,32,1
3,1,89,66,23,94,28.1,0.167,21,0
4,0,137,40,35,168,43.1,2.288,33,1
...,...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63,0
764,2,122,70,27,0,36.8,0.340,27,0
765,5,121,72,23,112,26.2,0.245,30,0
766,1,126,60,0,0,30.1,0.349,47,1
767,1,93,70,31,0,30.4,0.315,23,0

In [ ]:
diabetes_data.describe()

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age,Outcome
count,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000,768.000000
mean,3.845052,120.894531,69.105469,20.536458,79.799479,31.992578,0.471876,33.240885,0.348958
std,3.369578,31.972618,19.355807,15.952218,115.244002,7.884160,0.331329,11.760232,0.476951
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.078000,21.000000,0.000000
25%,1.000000,99.000000,62.000000,0.000000,0.000000,27.300000,0.243750,24.000000,0.000000
50%,3.000000,117.000000,72.000000,23.000000,30.500000,32.000000,0.372500,29.000000,0.000000
75%,6.000000,140.250000,80.000000,32.000000,127.250000,36.600000,0.626250,41.000000,1.000000
max,17.000000,199.000000,122.000000,99.000000,846.000000,67.100000,2.420000,81.000000,1.000000

## Features y Targets

In [ ]:
X = diabetes_data.drop(columns=["Outcome"])

In [ ]:
X

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
0,6,148,72,35,0,33.6,0.627,50
1,1,85,66,29,0,26.6,0.351,31
2,8,183,64,0,0,23.3,0.672,32
3,1,89,66,23,94,28.1,0.167,21
4,0,137,40,35,168,43.1,2.288,33
...,...,...,...,...,...,...,...,...
763,10,101,76,48,180,32.9,0.171,63
764,2,122,70,27,0,36.8,0.340,27
765,5,121,72,23,112,26.2,0.245,30
766,1,126,60,0,0,30.1,0.349,47
767,1,93,70,31,0,30.4,0.315,23

In [ ]:
y = diabetes_data["Outcome"]

In [ ]:
y

0      1
1      0
2      1
3      0
4      1
      ..
763    0
764    0
765    0
766    1
767    0
Name: Outcome, Length: 768, dtype: int64

## Train Test Split

In [ ]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=42)

In [ ]:
X_train

,Pregnancies,Glucose,BloodPressure,SkinThickness,Insulin,BMI,DiabetesPedigreeFunction,Age
60,2,84,0,0,0,0.0,0.304,21
618,9,112,82,24,0,28.2,1.282,50
346,1,139,46,19,83,28.7,0.654,22
294,0,161,50,0,0,21.9,0.254,65
231,6,134,80,37,370,46.2,0.238,46
...,...,...,...,...,...,...,...,...
71,5,139,64,35,140,28.6,0.411,26
106,1,96,122,0,0,22.4,0.207,27
270,10,101,86,37,0,45.6,1.136,38
435,0,141,0,0,0,42.4,0.205,29
102,0,125,96,0,0,22.5,0.262,21

In [ ]:
# KNN = K Nearest Neighbors

from sklearn.neighbors import KNeighborsClassifier


test_scores = []
train_scores = []

for i in range(1,15):

    knn = KNeighborsClassifier(i)

    # Entrenamiento
    knn.fit(X_train,y_train)
    
    train_scores.append(knn.score(X_train,y_train))
    test_scores.append(knn.score(X_test,y_test))

In [ ]:
for i, train_s, test_s in zip(range(1,15), train_scores, test_scores):

  print("KNN # de Componentes:", i, "Exactitud de Entrenamiento:", train_s, "Exactitud de Evaluacion:", test_s)

KNN # de Componentes: 1 Exactitud de Entrenamiento: 1.0 Exactitud de Evaluacion: 0.6753246753246753
KNN # de Componentes: 2 Exactitud de Entrenamiento: 0.8322475570032574 Exactitud de Evaluacion: 0.7012987012987013
KNN # de Componentes: 3 Exactitud de Entrenamiento: 0.8550488599348535 Exactitud de Evaluacion: 0.6493506493506493
KNN # de Componentes: 4 Exactitud de Entrenamiento: 0.8094462540716613 Exactitud de Evaluacion: 0.7077922077922078
KNN # de Componentes: 5 Exactitud de Entrenamiento: 0.7980456026058632 Exactitud de Evaluacion: 0.6623376623376623
KNN # de Componentes: 6 Exactitud de Entrenamiento: 0.7882736156351792 Exactitud de Evaluacion: 0.7272727272727273
KNN # de Componentes: 7 Exactitud de Entrenamiento: 0.7931596091205212 Exactitud de Evaluacion: 0.6883116883116883
KNN # de Componentes: 8 Exactitud de Entrenamiento: 0.7768729641693811 Exactitud de Evaluacion: 0.7467532467532467
KNN # de Componentes: 9 Exactitud de Entrenamiento: 0.7931596091205212 Exactitud de Evaluacion: 0.7207792207792207
KNN # de Componentes: 10 Exactitud de Entrenamiento: 0.7899022801302932 Exactitud de Evaluacion: 0.7662337662337663
KNN # de Componentes: 11 Exactitud de Entrenamiento: 0.7866449511400652 Exactitud de Evaluacion: 0.7337662337662337
KNN # de Componentes: 12 Exactitud de Entrenamiento: 0.7833876221498371 Exactitud de Evaluacion: 0.7792207792207793
KNN # de Componentes: 13 Exactitud de Entrenamiento: 0.7899022801302932 Exactitud de Evaluacion: 0.7727272727272727
KNN # de Componentes: 14 Exactitud de Entrenamiento: 0.7899022801302932 Exactitud de Evaluacion: 0.7727272727272727